"""Rebuild the A.E.B contract mirror from the AstrBotEX canonical module.

B00 requires that AstrBotEX and A.E.B parse the same payload into the same
result. The mechanism is a byte-identical copy of one self-contained module,
generated by this script, so the two sides cannot drift.

Usage (from the AstrBotEX repository root):

    python scripts/sync_contract_mirror.py --mirror PATH
    python scripts/sync_contract_mirror.py --verify --mirror PATH

The explicit target must be inside the caller's assigned workspace.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

CANONICAL = Path(__file__).resolve().parents[1] / "astrbot_ex" / "core" / "contracts.py"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify", action="store_true", help="only compare, do not write")
    parser.add_argument("--mirror", required=True, type=Path, help="explicit mirror target file")
    args = parser.parse_args(argv)

    if not CANONICAL.is_file():
        print(f"canonical module not found: {CANONICAL}", file=sys.stderr)
        return 2

    source = CANONICAL.read_bytes()
    mirror = args.mirror

    if args.verify:
        if not mirror.is_file():
            print(f"mirror missing: {mirror}", file=sys.stderr)
            return 1
        if mirror.read_bytes() != source:
            print("mirror drifted from canonical module", file=sys.stderr)
            return 1
        print(f"mirror in sync: {sha256(mirror)}")
        return 0

    mirror.parent.mkdir(parents=True, exist_ok=True)
    mirror.write_bytes(source)
    print(f"wrote {mirror}")
    print(f"sha256 {sha256(mirror)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
